"""Module 18: FUTURISTIC REPORTING ENGINE (Pure Python)."""
from __future__ import annotations
import os, sys, json, csv, time, html, glob, re, datetime
from core.banner import Colors
from core import __version__, __codename__

REPORTS_DIR = "reports"
if not os.path.exists(REPORTS_DIR):
    os.makedirs(REPORTS_DIR)

# --- HELPER FUNCTIONS ---
def get_timestamp():
    return datetime.datetime.now().strftime("%Y%m%d_%H%M%S")

def get_readable_time():
    return datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

# --- 1. JSON REPORT BUILDER ---
def build_json_report(data: dict, filename: str = None):
    print(f"\n{Colors.cyan('[+]')} Building JSON Report...")
    if not filename:
        filename = f"{REPORTS_DIR}/report_{get_timestamp()}.json"
    
    report = {
        "meta": {
            "tool": f"Pareek Security Kit v{__version__}",
            "codename": __codename__,
            "generated_at": get_readable_time(),
            "analyst": "PSK User"
        },
        "data": data
    }
    
    with open(filename, "w") as f:
        json.dump(report, f, indent=4, default=str)
    print(f"  {Colors.green('[+] Saved:')} {filename}")
    return filename

# --- 2. HTML DASHBOARD GENERATOR ---
def build_html_report(data: dict, filename: str = None):
    print(f"\n{Colors.cyan('[+]')} Building HTML Dashboard...")
    if not filename:
        filename = f"{REPORTS_DIR}/dashboard_{get_timestamp()}.html"
    
    # Convert data to HTML
    rows = ""
    for k, v in data.items():
        if isinstance(v, (list, dict)):
            v = json.dumps(v)[:100] + "..."
        rows += f"<tr><td><strong>{html.escape(str(k))}</strong></td><td>{html.escape(str(v))}</td></tr>\n"
    
    html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>PSK Report - {get_readable_time()}</title>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: 'Segoe UI', sans-serif; background: #0a0e27; color: #c9d1d9; padding: 20px; }}
  .header {{ background: linear-gradient(135deg, #ff00ff, #00ffff); padding: 30px; border-radius: 15px; text-align: center; margin-bottom: 20px; }}
  .header h1 {{ color: #fff; font-size: 32px; text-shadow: 2px 2px 8px rgba(0,0,0,0.5); }}
  .header p {{ color: #fff; opacity: 0.9; margin-top: 10px; }}
  .card {{ background: #161b22; border-radius: 10px; padding: 20px; margin-bottom: 20px; border-left: 4px solid #00ffff; }}
  .card h2 {{ color: #00ffff; margin-bottom: 15px; }}
  table {{ width: 100%; border-collapse: collapse; }}
  th, td {{ padding: 12px; text-align: left; border-bottom: 1px solid #30363d; }}
  th {{ background: #21262d; color: #ff00ff; }}
  tr:hover {{ background: #1f2937; }}
  .footer {{ text-align: center; color: #6e7681; margin-top: 30px; padding: 20px; }}
  .badge {{ display: inline-block; padding: 4px 12px; border-radius: 12px; background: #00ffff; color: #0a0e27; font-size: 12px; font-weight: bold; }}
</style>
</head>
<body>
  <div class="header">
    <h1>🛡️ PAREEK SECURITY KIT</h1>
    <p>v{__version__} · {__codename__} · {get_readable_time()}</p>
  </div>
  <div class="card">
    <h2>📊 Report Data</h2>
    <span class="badge">{len(data)} ENTRIES</span>
    <table>
      <thead><tr><th>Field</th><th>Value</th></tr></thead>
      <tbody>{rows}</tbody>
    </table>
  </div>
  <div class="footer">
    <p>Generated by Pareek Security Kit v{__version__} · For authorized testing only</p>
  </div>
</body>
</html>
"""
    with open(filename, "w") as f:
        f.write(html_content)
    print(f"  {Colors.green('[+] Saved:')} {filename}")
    print(f"  {Colors.dim('Open in browser: termux-open ' + filename)}")
    return filename

# --- 3. TEXT REPORT GENERATOR ---
def build_text_report(data: dict, filename: str = None):
    print(f"\n{Colors.cyan('[+]')} Building Text Report...")
    if not filename:
        filename = f"{REPORTS_DIR}/report_{get_timestamp()}.txt"
    
    border = "=" * 70
    report = f"""
{border}
    PAREEK SECURITY KIT v{__version__} - SECURITY ASSESSMENT REPORT
{border}
Generated: {get_readable_time()}
Codename:  {__codename__}
Analyst:   PSK User

{border}
    EXECUTIVE SUMMARY
{border}
Total Findings: {len(data)}
Report Type: Security Assessment

{border}
    DETAILED FINDINGS
{border}
"""
    for i, (k, v) in enumerate(data.items(), 1):
        report += f"\n[{i}] {k}\n"
        report += "-" * 70 + "\n"
        if isinstance(v, (list, dict)):
            report += json.dumps(v, indent=4, default=str) + "\n"
        else:
            report += str(v) + "\n"
    
    report += f"\n{border}\n"
    report += "DISCLAIMER: This report is for authorized security testing only.\n"
    report += f"{border}\n"
    
    with open(filename, "w") as f:
        f.write(report)
    print(f"  {Colors.green('[+] Saved:')} {filename}")
    return filename

# --- 4. CSV EXPORT ---
def build_csv_report(data: dict, filename: str = None):
    print(f"\n{Colors.cyan('[+]')} Building CSV Report...")
    if not filename:
        filename = f"{REPORTS_DIR}/report_{get_timestamp()}.csv"
    
    with open(filename, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["Field", "Value", "Data Type", "Timestamp"])
        for k, v in data.items():
            if isinstance(v, (list, dict)):
                val = json.dumps(v, default=str)[:500]
                dtype = "JSON"
            else:
                val = str(v)
                dtype = type(v).__name__
            writer.writerow([k, val, dtype, get_readable_time()])
    
    print(f"  {Colors.green('[+] Saved:')} {filename}")
    return filename

# --- 5. EXECUTIVE SUMMARY ---
def executive_summary(data: dict):
    print(f"\n{Colors.cyan('[+]')} Generating Executive Summary...")
    print(f"\n{Colors.magenta('=' * 60)}")
    print(f"  {Colors.bold('EXECUTIVE SUMMARY')}")
    print(f"{Colors.magenta('=' * 60)}")
    print(f"  {Colors.green('Date:')} {get_readable_time()}")
    print(f"  {Colors.green('Tool:')} Pareek Security Kit v{__version__}")
    print(f"  {Colors.green('Total Findings:')} {len(data)}")
    
    # Risk assessment
    risk = "LOW"
    if len(data) > 10: risk = "MEDIUM"
    if len(data) > 25: risk = "HIGH"
    
    color = Colors.green if risk == "LOW" else Colors.yellow if risk == "MEDIUM" else Colors.red
    print(f"  {Colors.green('Overall Risk:')} {color(risk)}")
    
    print(f"\n  {Colors.magenta('--- Key Findings ---')}")
    for i, (k, v) in enumerate(list(data.items())[:10], 1):
        print(f"  {Colors.green(str(i) + '.')} {k}")
    
    print(f"\n  {Colors.magenta('--- Recommendations ---')}")
    print(f"  • Review and remediate all HIGH severity findings")
    print(f"  • Apply latest security patches")
    print(f"  • Conduct regular security audits")
    print(f"  • Implement defense-in-depth strategy")
    print(f"{Colors.magenta('=' * 60)}\n")

# --- 6. REPORT MANAGER ---
def report_manager():
    while True:
        print(f"\n{Colors.magenta('═' * 60)}")
        print(f"  {Colors.bold('REPORT MANAGER')}")
        print(f"{Colors.magenta('═' * 60)}")
        print(f"  {Colors.green('1.')} List All Reports")
        print(f"  {Colors.green('2.')} View Report")
        print(f"  {Colors.green('3.')} Delete Report")
        print(f"  {Colors.green('4.')} Clean All Reports")
        print(f"  {Colors.green('0.')} Back")
        print(f"{Colors.magenta('─' * 60)}")
        
        choice = input(Colors.bold(Colors.cyan("  [ReportManager]> "))).strip()
        if choice == "0": break
        elif choice == "1":
            files = glob.glob(f"{REPORTS_DIR}/*")
            if not files:
                print(f"  {Colors.yellow('[-] No reports found.')}"); continue
            print(f"\n  {Colors.green(f'Found {len(files)} reports:')}")
            for i, f in enumerate(sorted(files, key=os.path.getmtime, reverse=True), 1):
                size = os.path.getsize(f) / 1024
                mtime = datetime.datetime.fromtimestamp(os.path.getmtime(f)).strftime("%Y-%m-%d %H:%M")
                print(f"  {Colors.green(str(i) + '.')} {os.path.basename(f)}")
                print(f"     {Colors.dim(f'{size:.2f} KB | {mtime}')}")
        elif choice == "2":
            fname = input(Colors.bold(Colors.yellow("  [?] Enter filename: "))).strip()
            path = f"{REPORTS_DIR}/{fname}" if not fname.startswith(REPORTS_DIR) else fname
            if os.path.exists(path):
                with open(path) as f: print(f"\n{Colors.dim(f.read()[:2000])}")
            else:
                print(f"  {Colors.red('[!] File not found.')}")
        elif choice == "3":
            fname = input(Colors.bold(Colors.yellow("  [?] Enter filename to delete: "))).strip()
            path = f"{REPORTS_DIR}/{fname}" if not fname.startswith(REPORTS_DIR) else fname
            if os.path.exists(path):
                os.remove(path)
                print(f"  {Colors.green('[+] Deleted:')} {fname}")
            else:
                print(f"  {Colors.red('[!] File not found.')}")
        elif choice == "4":
            confirm = input(Colors.bold(Colors.red("  [!] Delete ALL reports? Type 'YES': "))).strip()
            if confirm == "YES":
                for f in glob.glob(f"{REPORTS_DIR}/*"):
                    os.remove(f)
                print(f"  {Colors.green('[+] All reports deleted.')}")

# --- 7. AUTO SCAN + FULL REPORT ---
def auto_scan_and_report(target: str):
    print(f"\n{Colors.cyan('[+]')} Auto Scan + Full Report: {Colors.bold(target)}")
    print(f"  {Colors.dim('Running all relevant modules and collecting data...')}")
    
    all_data = {
        "target": target,
        "scan_started": get_readable_time(),
        "info_gathering": {},
        "dns_records": {},
        "ssl_info": {},
        "http_headers": {},
    }
    
    # Try each module safely
    try:
        from modules.information_gathering.engine import resolve_dns
        import socket
        d = target.replace("https://", "").replace("http://", "").split("/")[0]
        try:
            ips = socket.gethostbyname_ex(d)
            all_data["info_gathering"] = {"hostname": ips[0], "ips": ips[2]}
            print(f"  {Colors.green('[✓]')} DNS resolved")
        except: pass
    except: pass
    
    try:
        import dns.resolver
        d = target.replace("https://", "").replace("http://", "").split("/")[0]
        for rec in ['A', 'MX', 'NS', 'TXT']:
            try:
                answers = dns.resolver.resolve(d, rec, lifetime=3)
                all_data["dns_records"][rec] = [str(a) for a in answers]
            except: pass
        print(f"  {Colors.green('[✓]')} DNS records collected")
    except: pass
    
    try:
        import requests
        url = target if target.startswith("http") else f"https://{target}"
        resp = requests.get(url, timeout=10, allow_redirects=True)
        all_data["http_headers"] = dict(resp.headers)
        all_data["http_status"] = resp.status_code
        print(f"  {Colors.green('[✓]')} HTTP headers collected")
    except: pass
    
    try:
        import ssl, socket
        d = target.replace("https://", "").replace("http://", "").split("/")[0]
        ctx = ssl.create_default_context()
        with ctx.wrap_socket(socket.socket(), server_hostname=d) as s:
            s.settimeout(10)
            s.connect((d, 443))
            cert = s.getpeercert()
            all_data["ssl_info"] = {
                "issuer": dict(x[0] for x in cert.get('issuer', [])),
                "notAfter": cert.get('notAfter', 'N/A'),
                "notBefore": cert.get('notBefore', 'N/A')
            }
        print(f"  {Colors.green('[✓]')} SSL certificate collected")
    except: pass
    
    all_data["scan_completed"] = get_readable_time()
    
    # Generate all report formats
    print(f"\n  {Colors.magenta('--- Generating Reports ---')}")
    base = target.replace("https://", "").replace("http://", "").replace("/", "_").replace(".", "_")
    ts = get_timestamp()
    build_json_report(all_data, f"{REPORTS_DIR}/{base}_{ts}.json")
    build_html_report(all_data, f"{REPORTS_DIR}/{base}_{ts}.html")
    build_text_report(all_data, f"{REPORTS_DIR}/{base}_{ts}.txt")
    build_csv_report(all_data, f"{REPORTS_DIR}/{base}_{ts}.csv")
    executive_summary(all_data)
    print(f"\n  {Colors.green('[✓] All reports generated successfully!')}")

# --- MENU ---
def run_reporting():
    while True:
        print(f"\n{Colors.magenta('═' * 60)}")
        print(f"  {Colors.bold('MODULE 18: FUTURISTIC REPORTING')}")
        print(f"{Colors.magenta('═' * 60)}")
        print(f"  {Colors.green('1.')} Auto Scan + Full Report (All Formats)")
        print(f"  {Colors.green('2.')} Generate JSON Report")
        print(f"  {Colors.green('3.')} Generate HTML Dashboard")
        print(f"  {Colors.green('4.')} Generate Text Report")
        print(f"  {Colors.green('5.')} Generate CSV Export")
        print(f"  {Colors.green('6.')} Executive Summary")
        print(f"  {Colors.green('7.')} Report Manager")
        print(f"  {Colors.red('0.')} Back to Main Menu")
        print(f"{Colors.magenta('─' * 60)}")
        
        choice = input(Colors.bold(Colors.cyan("  [Reporting]> "))).strip()
        if choice == "0": break
        elif choice == "1":
            target = input(Colors.bold(Colors.yellow("  [?] Enter Target (domain/URL): "))).strip()
            if target: auto_scan_and_report(target)
        elif choice in ("2","3","4","5"):
            print(f"  {Colors.dim('Generating with sample data...')}")
            sample = {
                "target": "example.com",
                "scan_date": get_readable_time(),
                "findings": ["Open port 22", "Missing HSTS header", "Outdated TLS 1.0"]
            }
            if choice == "2": build_json_report(sample)
            elif choice == "3": build_html_report(sample)
            elif choice == "4": build_text_report(sample)
            elif choice == "5": build_csv_report(sample)
        elif choice == "6":
            sample = {"Finding 1": "Open port", "Finding 2": "Missing header", "Finding 3": "Weak TLS"}
            executive_summary(sample)
        elif choice == "7": report_manager()
        else: print(f"  {Colors.red('[!] Invalid option.')}")
